export default {
    defaultLocale: "en",
    settingsIsModal: false,
    pageState: false,
    defaultGroups: [],
    defaultStudents: [],
    allUsers:[],
    allClicks:[],
    timeStundentsMode:0,
    timeCalculatorMode:0,
    timePaintMode:0,
    timeConverterMode:0,
    defaultTeacher: 0,
    activeGroup:0,
    modesWindow: false,
    buttonsStudent:false,
    modalOkCancel:false,
    currentStudent:0,
    currentMode:"table",
    groupToDelete:0,
    onlineTeachers:[],
    modal:0,
    isConvLength:true,
    checkStatic: false,
    checkAdditional: false,
    infoTeacher: null,
    buttonImageState:false,
    notificationState:true,
    defaultChats: [],
    defaultUsers: [],
    defaultActiveChat: 0,
    defaultIsRead: true,
    inputs: [
        { keyDown: "checkEnterDataStudents", type: "text", placeholderKey:"NameStudent", id:"nameStudent", labelText:"NameStudent", classDiv:"registration-form__item", classInput: "custom-input" },
        { classDivOutput: 'registration-output-block', keyDown: "checkEnterDataStudents", type: "text", placeholderKey:"SurnameStudent", id:"surnameStudent", labelText:"SurnameStudent", classDiv:"registration-form__item", classInput: "custom-input" },
        { classDivOutput: 'registration-output-block', keyDown: "checkEnterAgeStudent", type: "text", placeholderKey:"AgeStudent", id:"ageStudent", labelText:"AgeStudent", classDiv:"registration-form__item", classInput: "custom-input" },
        { classDivOutput: 'registration-output-block', keyDown: "checkEnterDataStudents", type: "text", placeholderKey:"CityStudent", id:"cityStudent", labelText:"CityStudent", classDiv:"registration-form__item", classInput: "custom-input" },
         ],
    buttonsTable: [
        {name: 'createStudentBtn', resourceKey: "createStudent", classButton: 'custom-button-modal',  classDiv: 'button-wrapper'},
        {name: 'clearStudentsBtn', resourceKey: "clearStudent", classButton: 'custom-button-modal',  classDiv: 'button-wrapper'}
    ],
    divsTable:[
        { name: 'idTable', resourceKey: "idTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
        { name: 'nameHeaderTable', resourceKey: "nameHeaderTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
        { name: 'surnameHeaderTable', resourceKey: "surnameHeaderTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
        { name: 'ageHeaderTable', resourceKey: "ageHeaderTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
        { name: 'cityHeaderTable', resourceKey: "cityHeaderTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
        { name: 'buttonsHeaderTable', resourceKey: "buttonsHeaderTable", classButton: 'custom-button',  classDiv: 'button-wrapper'},
    ],
    area: [
        { placeholderKey: 'textArea', titleAdditional: 'titleAdditional', classTextArea: 'text-area', nameButton: 'change', nameButtons: 'save', classButton: 'custom-button change-buttons',  classDiv: 'div-box-my-account', callbackOnClick: 'changeButton' },
    ],
    inputMy: [
        { clickContextMenu: 'openContextMenu', labelClass: 'label-account', classDiv: 'static-info-block', labelText: 'login', buttonNameSave: 'save', buttonNameChange: 'change', callbackOnClick2: 'saveButton', callbackOnClick: 'changeButton',
            classButton: 'custom-button change-buttons', imgSrc: 'robin.png', classImg: 'my-account-logo-page', classNameInput: 'custom-input input-account', inputType: 'text', placeholderKey: 'login', inputId: 'loginMyAcc', callbackOnKeyDown: 'checkEnterLogin'},
        { labelClass: 'label-account', classDiv: 'static-info', labelText: 'email', classNameInput: 'custom-input input-account', inputType: 'text', placeholderKey: 'email', inputId: 'mailMyAcc', callbackOnKeyDown: 'deleteRedBorder' },
        { classDiv: 'static-info', labelText: 'phone_number', classNameInput: 'custom-input input-account', inputType: 'text', placeholderKey: 'phone', inputId: 'phoneMyAcc', callbackOnKeyDown: 'checkEnterPhone'},
    ],
    divsAdminTable:[
        { name: 'loginHeaderTable', resourceKey: "Login", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'activeSesHeaderTable', resourceKey: "Active Session", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'popularModeHeaderTable', resourceKey: "Popular Mode", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'crudHeaderTable', resourceKey: "CRUD", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'deviceHeaderTable', resourceKey: "Device", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'geoLocHeaderTable', resourceKey: "GeoLoc", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'publicIpHeaderTable', resourceKey: "Public IP", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'browserNameHeaderTable', resourceKey: "Browser", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
        { name: 'messagesNameHeaderTable', resourceKey: "IsChat", classButton: 'custom-button',  classDiv: 'custom-input-admin'},
    ],
}

