export default {
    resources: {
        login: "Login",
        email: "Email",
        phone_number: "Phone",
        rightsFooter:"All rights reserved ",
        developersFooter:"Developers: Pryvalov Bogdan, Sorobei Bohdan",
        testersFooter:"Testers: Adonkina Eleonora, Franko Andrey",
        langEn:"en",
        langRu:"ru",
        langAr:"ar",
        valueSelectEn:"en",
        valueSelectRu:"ru",
        valueSelectAr:"ar",
        modalSettingsText:"Settings",
        modalSettingsMainText:"Choose language",
        NameStudent:"Name",
        SurnameStudent:"Surname",
        AgeStudent:"Age",
        CityStudent:"City",
        createStudentBtn:"Create",
        clearStudentsBtn:"Clear",
        controlPanel:"Control panel",
        addStudentTable:"Add student",
        nameHeaderTable:"Name",
        surnameHeaderTable:"Surname",
        ageHeaderTable:"Age",
        cityHeaderTable:"City",
        idTable:"Number",
        buttonsHeaderTable:"Button",
        titleAdditional: 'Additional info',
        updateStudentBtn:"Update",
        deleteStudentBtn:"Delete",
        okStudentBtn:"Ok",
        cancelStudentBtn:"Cancel",
        clearTextTable:"Are you sure you want to clear all students from group?",
        deleteTextTable:"Are you sure you want to delete group and all students in it?",
        resetSettingsTextTable:"Are you sure you want to delete all groups and clear settings ?",
        change: 'Change',
        save: 'Save',
        notifications:"Notifications",
        resetBtn:"Reset",
        updateNotification:" was changed: ",
        deleteNotification:" was deleted",
        createStudentNotification:" student was created",
        modes:"Modes",
        tableMode:"Students",
        paintMode:"Paint",
        calculatorMode:"Calculator",
        converterMode:"Converter",
        controlPanelPaint:"Control panel",
        lineThickness:"Line thickness",
        lineColor:"Line color",
        converterLength: 'Converter length',
        convert: 'Convert',
        meter: "Meter",
        verst: "Verst",
        mile: "Mile",
        foot: "Foot",
        yard: "yard",
        ConverterCurrency: 'Converter currency',
        coverter: "Converter",
        chats:"Chats",
        online:"Online users",
        leaveChat:"Leave chat",
        sendBtnChat:"Send message",
        horizontalLineButton: 'Horizontal line',
        squareButton: 'Square',
        rectangleButton: 'Rectangle',
        triangleButton: 'Triangle',
        circleButton: 'Circle',
        fillButton: 'Fill',
        pencilButton: 'Pencil',
        figureSize: 'Figure size',
        gameBalls:"Game balls",
    },
    dialogs: {
        phoneOutput: 'Invalid phone number',
        keyWordOutput: 'The keyword needed  for password recovery',

    },
    placeholders: {
        login: "Enter your login here...",
        email: "Enter your email here...",
        phone: "Enter phone number",

        NameStudent:"Enter name of student",
        SurnameStudent:"Enter surname of student",
        AgeStudent:"Enter age of student",
        CityStudent:"Enter city of student",
        textArea: 'Here you can enter more information about yourself',
        converterLength: "Write value to convert",
        converterResult: "Result",
        chatPlace: "Enter your message here...",
    }
}