export default {
    resources: {
        login: "Логин",
        email: "Емейл",
        phone_number: "Телефон",
        rightsFooter:"Все права защищены ",
        developersFooter:"Разработчики: Привалов Богдан, Соробей Богдан",
        testersFooter:"Тестировщики: Адонкина Элеонора, Франко Андрей",
        langEn:"Англ",
        langRu:"Русс",
        langAr:"Араб",
        valueSelectEn:"en",
        valueSelectRu:"ru",
        valueSelectAr:"ar",
        modalSettingsText:"Настройки",
        modalSettingsMainText:"Выберите язык",
        NameStudent:"Имя",
        SurnameStudent:"Фимилия",
        AgeStudent:"Возраст",
        CityStudent:"Город",
        createStudentBtn:"Создать",
        clearStudentsBtn:"Очистить",
        controlPanel:"Контрольная панель",
        addStudentTable:"Добавить студента",
        nameHeaderTable:"Имя",
        surnameHeaderTable:"Фимилия",
        ageHeaderTable:"Возраст",
        cityHeaderTable:"Город",
        idTable:"Нумерация",
        buttonsHeaderTable:"Кнопки",
        titleAdditional: 'Доп информация',
        updateStudentBtn:"Обновить",
        deleteStudentBtn:"Удалить",
        okStudentBtn:"Подтвердить",
        cancelStudentBtn:"Отменить",
        clearTextTable:"Вы уверены что вы хотите удалить всех студентов с группы?",
        deleteTextTable:"Вы уверены что вы хотите удалить группу и всех студентов в ней?",
        resetSettingsTextTable:"Вы уверены что вы хотите удалить все группы и обнулить настройки?",
        change: 'Изменить',
        save: 'Сохранить',
        notifications:"Уведомления",
        resetBtn:"Обнулить",
        updateNotification:" был изменен на ",
        deleteNotification:" был удален",
        createStudentNotification:" студент был создан",
        modes:"Моды",
        tableMode:"Студенты",
        paintMode:"Рисовалка",
        calculatorMode:"Калькулятор",
        converterMode:"Конвертер",
        controlPanelPaint:"Контрольная панель",
        lineThickness:"Толщина линии",
        lineColor:"Цвет линии",
        converterLength: 'Конвертер длин',
        convert: 'Конвертировать',
        meter: "Метры",
        verst: "Версты",
        mile: "Мили",
        foot: "Футы",
        yard: "Ярды",
        ConverterCurrency: 'Конвертер валют',
        coverter: "Конвертер",
        chats:"Чаты",
        online:"Пользователи онлайн",
        leaveChat:"Выйти",
        sendBtnChat:"Отправить сообщение",
        horizontalLineButton: 'Горизонтальная линия',
        squareButton: 'Квадрат',
        rectangleButton: 'Прямоугольник',
        triangleButton: 'Треугольник',
        circleButton: 'Круг',
        fillButton: 'Заливка',
        pencilButton: 'Карандаш',
        figureSize: 'Размер фигуры',
        gameBalls:"Игра-шары",
    },
    dialogs: {
        phoneOutput: 'Не корректный номер',
        keyWordOutput: 'Ключевое слово, необходимое для восстановления пароля',
    },
    placeholders: {
        login: "Введите свой логин здесь...",
        email: "Введите свой емейл здесь...",
        phone: "Введите номер телефона",
        NameStudent:"Введите имя студента",
        SurnameStudent:"Введите фамилию студента",
        AgeStudent:"Введите возраст студента",
        CityStudent:"Введите город студента",
        textArea: 'Здесь вы можете ввести больше информации о себе',
        converterLength: "Введите значение для конвертации",
        converterResult: "Результат",
        chatPlace: "Введите ваше сообщение...",
    }
}