export default {
    resources: {
        login: "Login",
        password: "Password",
        email: "Email",
        keyword: "Keyword",
        backToAuth: "Back to authorization",
        registration: "Sign up",
        secondPassword: "Confirm password",
        phone: "Phone number",
        loginAuth:"Log In",
        registrationAuth:"Registration",
        forgottenPassword:"Forgotten Password",
        authLogin:"Login",
        authPassword:"Password",
        authMessage:"correct login",
        authMessageError:"Insert correct login or password",
        authorizationTitle:"Authorization",
        rightsFooter:"All rights reserved ",
        developersFooter:"Developers: Pryvalov Bogdan, Sorobei Bohdan",
        testersFooter:"Testers: Adonkina Eleonora, Franko Andrey",
        langEn:"en",
        langRu:"ru",
        langAr:"ar",
        valueSelectEn:"en",
        valueSelectRu:"ru",
        valueSelectAr:"ar",
        modalSettingsText:"Settings",
        modalSettingsMainText:"Choose language",
        errorLoginRequest:"Insert correct login or password!!!",
        registrationSuccessMessage:"Registration successful",
        registrationErrormessage:"Write correct values",
        createStudentBtn:"Create",
        clearStudentsBtn:"Clear",
        yourPassword: 'Your Password',
        forgotButton: 'Get password',
        forgotPassword: 'Password recovery',
    },
    dialogs: {
        forgotPassword: "If you forgot password",
        loginOutput: 'Invalid login',
        passwordOutput: 'Invalid password',
        secondPasswordOutput: 'Passwords do not match',
        mailOutput: 'Invalid E-mail',
        phoneOutput: 'Invalid phone number',
        keyWordOutput: 'The keyword needed  for password recovery',

    },
    placeholders: {
        login: "Enter your login here...",
        email: "Enter your email here...",
        password: "Enter your password here...",
        secondPassword: "Enter your password again...",
        phone: "Phone number",
        keyword: "Enter your key word...",
        authLogin:"Enter your login",
        authPassword: "Enter your password",
    }
}