export default {
    resources: {
        login: "Логин",
        password: "Пароль",
        email: "Емейл",
        keyword: "Ключевое слово",
        backToAuth: "Вернуться на авторизацию",
        registration: "Зарегестрироваться",
        secondPassword: "Подтвердите пароль",
        phone: "Номер телефона",
        loginAuth:"Войти",
        registrationAuth:"Регистрация",
        forgottenPassword:"Забыли пароль",
        authLogin:"Логин",
        authPassword:"Пароль",
        authMessage:"correct login",
        authMessageError:"Введите верный логин или пароль!!!",
        authorizationTitle:"Авторизация",
        rightsFooter:"Все права защищены ",
        developersFooter:"Разработчики: Привалов Богдан, Соробей Богдан",
        testersFooter:"Тестировщики: Адонкина Элеонора, Франко Андрей",
        langEn:"Англ",
        langRu:"Русс",
        langAr:"Араб",
        valueSelectEn:"en",
        valueSelectRu:"ru",
        valueSelectAr:"ar",
        modalSettingsText:"Настройки",
        modalSettingsMainText:"Выберите язык",
        errorLoginRequest:"Введите правильный логин или пароль!!!",
        registrationSuccessMessage:"Регистрация успешна",
        registrationErrormessage:"Введите верные значения!!!",
        createStudentBtn:"Создать",
        clearStudentsBtn:"Очистить",
        yourPassword: 'Ваш Пароль',
        forgotButton: 'Получить пароль',
        forgotPassword: 'Восстановление пароля',
    },
    dialogs: {
        forgotPassword: "Если Вы забыли пароль",
        loginOutput: 'Не корректный логин',
        passwordOutput: 'Не корректный пароль',
        secondPasswordOutput: 'Пароли не совпадают',
        mailOutput: 'Не корректный E-mail',
        phoneOutput: 'Не корректный номер',
        keyWordOutput: 'Ключевое слово, необходимое для восстановления пароля',
    },
    placeholders: {
        login: "Введите свой логин здесь...",
        email: "Введите свой емейл здесь...",
        password: "Введите свой пароль здесь...",
        secondPassword: "Введите свой пароль ещё раз...",
        phone: "Номер телефона",
        keyword: "Введите Ваше ключевое слово...",
        authLogin:"Введите ваш логин",
        authPassword: "Введите ваш пароль",
    }
}