module.exports = {
    port:3000,
    authorizationUrl:"/authorization",
    registrationUrl:"/registration",
    groupStudentUrl:"/groupStudent",
    getAllGroupsUrl:"/getAllGroups",
    accountSettingUrl:"/accountSetting",
    groupsUrl:"/groups",
    insertStudentUrl:"/createStudent",
    updateStudentUrl:"/update",
    deleteStudentUrl:"/delete",
    accountupdateUrl:"/accountupdate",
    forgottenPassUrl:"/for",
    deleteGroupUrl:"/deleteGroup",
    clearStudentsUrl:"/studentclear",
    updateGroupUrl:"/updateGroup",
    sendImageUrl:"/sendImage",
    resetSettingsUrl:"/resetSettings",
    getInfoTeacherUrl: '/getInfoTeacher',
    updateInfoTeach: '/updateInfoTeacher',
    getPassword: '/getPassword',
};